spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root}
    url: jdbc:postgresql://localhost/db
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 8081
