spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root}
    url: jdbc:postgresql://localhost/db
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8080
