CREATE SEQUENCE IF NOT EXISTS account_seq AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE account
(
    id       INTEGER      NOT NULL,
    address  VARCHAR(255) NOT NULL,
    age      INTEGER      NOT NULL,
    email    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone    VARCHAR(255) NOT NULL
);
